version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "nuget"
    directory: "/build"
    schedule:
      interval: "monthly"

  - package-ecosystem: "nuget"
    directory: "/.config"
    schedule:
      interval: "monthly"
