name: build

on:
  push:
    branches:
      - master
  pull_request:

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
      - name: Build
        run: ./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: artifacts/*.nupkg
