name: build

on:
  push:
    branches:
      - master
  pull_request:

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 8.0.404
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 9.0.100
      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
      - name: Build
        run: ./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: artifacts/*.nupkg
