name: publish

on:
  release:
    types: [published]

env:
  DOTNET_NOLOGO: true

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
      - name: Install Mono
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-complete
      - name: Deploy
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: ./build.sh publish
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: artifacts/*.nupkg
